# Define all the training and testing hyperparameters here.

# Dataset config
data_path: /media/miquel/Pytorch-training-toolkit/data/MNIST


# Hyperparameter sweeper settings
defaults:
  - _self_
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    direction: "minimize"
    study_name: null
    storage: null
    n_trials: 20
    n_jobs: 2